services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\ApiContext:
        public: true
        arguments:
            - "@doctrine"
            - "@lexik_jwt_authentication.jwt_manager"
